# Generated by Django 4.2.11 on 2024-05-13 23:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(1, 'Iron'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Platinum'), (6, 'Emerald'), (7, 'Diamond'), (8, 'Master'), (9, 'Grandmaster'), (10, 'Challenger')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=30)),
                ('point', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_img', models.ImageField(blank=True, default='media/userProfile/default.png', null=True, upload_to='media/userProfile')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='수정일')),
                ('friends', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('usertier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.badage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
