# Generated by Django 4.2.11 on 2024-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommend_genre',
            field=models.ManyToManyField(to='movies.genre', verbose_name='genre_like_users'),
        ),
    ]
