# Generated by Django 4.2.11 on 2024-05-17 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='comment/%Y/%m/%d', verbose_name='댓글 이미지')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='코스명')),
                ('description', models.TextField(verbose_name='내용')),
                ('vote_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총 투표수')),
                ('is_reported', models.BooleanField(default=False, verbose_name='게시글 정지여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='코스 작성자')),
                ('comments', models.ManyToManyField(through='movies.Comment', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='liked_courses', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('reports', models.ManyToManyField(related_name='reported_courses', to=settings.AUTH_USER_MODEL, verbose_name='신고')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='영화 번호')),
                ('title', models.CharField(max_length=100, verbose_name='영화 제목')),
                ('overview', models.TextField(blank=True, verbose_name='영화 개요')),
                ('original_language', models.CharField(max_length=100, verbose_name='출시 국가')),
                ('release_date', models.DateField(verbose_name='개봉일')),
                ('popularity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='인기도')),
                ('vote_average', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='평점')),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='poster/%Y/%m/%d', verbose_name='포스터 이미지')),
                ('runtime', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='상영시간')),
                ('adult', models.BooleanField(default=True, verbose_name='성인영화 여부')),
                ('genres', models.ManyToManyField(related_name='moives', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_menu', models.CharField(choices=[('appetizer', 'Appetizer'), ('main', 'Main'), ('dessert', 'Dessert')], max_length=20, verbose_name='메뉴 종류')),
                ('title', models.CharField(max_length=200, verbose_name='메뉴 제목')),
                ('description', models.TextField(verbose_name='감상평')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='movies.course', verbose_name='코스')),
                ('movie', models.ForeignKey(default='삭제된 영화입니다.', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='menus', to='movies.movie', verbose_name='영화')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.course', verbose_name='코스'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sup_comment',
            field=models.ManyToManyField(null=True, to='movies.comment', verbose_name='상위 댓글'),
        ),
    ]
